name: Build and deploy Jekyll site to GitHub Pages

on: [push, pull_request]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - uses: limjh16/jekyll-action-ts@v2
      - uses: JamesIves/github-pages-deploy-action@4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: _site
